name: nodespen
description: La app de animación definitiva - Dibujo, Nodos y Gacha en una sola herramienta.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.2.1
  archive: ^3.6.1
  file_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon_app/nodespen_icon_app.png"
  adaptive_icon_background: "#1A1A2E"
  adaptive_icon_foreground: "assets/icon_app/nodespen_icon_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/default_content/
    - assets/icon_app/
  # fonts:
  #   - family: Nodespen
  #     fonts:
  #       - asset: assets/fonts/Nodespen-Regular.ttf
